name: Build Handbook

on: 
  push:
    branches:
      - main
      - test-actions
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  
  build_latex:
    
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: commit SHA
        id: sha
        run: echo "::set-output name=sha_short::${GITHUB_SHA:0:7}"
      - name: compile
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          working_directory: src/
          args: -xelatex -dvi- -time -latexoption=-file-line-error -output-directory=../build/ -latexoption=-interaction=nonstopmode -usepretex=\providecommand{\commitId}{${{ steps.sha.outputs.sha_short }}}
      - name: deploy
        uses: peaceiris/actions-gh-pages@latest
        with:
          personal_token: ${{ secrets.PUBLISH_TOKEN }}
          publish_dir: ./build
