name: Build Handbook

on: 
  push:
    branches:
      - main
      - test-actions
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  
  build_latex:
    
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: ensure permission
        run: chmod +x ./make.sh
      - name: compile
        uses: dante-ev/latex-action@latest
        with:
          entrypoint: ./make.sh
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PUBLISH_TOKEN }}
          publish_dir: ./build
