name: Build Handbook
on: 
  push:
    branches:
      - main
      - add-zhmakeindex-action
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  
  build_latex:
    
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: commit SHA
        id: sha
        run: echo "::set-output name=sha_short::${GITHUB_SHA:0:7}"
      - name: fetch zhmakeindex
        uses: robinraju/release-downloader@v1.4
        with:
          repository: leo-liu/zhmakeindex
          tag: zhmakeindex-1.2
          fileName: zhmakeindex-1.2.zip
      - name: unpack and setup
        run: unzip zhmakeindex-1.2.zip && chmod +x zhmakeindex/bin/linux_x64/zhmakeindex
      - name: pre-compile
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          working_directory: src/
          args: -xelatex -dvi- -time -latexoption=-file-line-error -output-directory=../build/ -latexoption=-interaction=nonstopmode
      - name: debug
        run: ls -al build
      - name: build index
        run: sudo chmod -R 666 build && sudo zhmakeindex/bin/linux_x64/zhmakeindex -s src/index-entry.ist -z pinyin build/main.idx
      - name: build
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          working_directory: src/
          args: -xelatex -dvi- -time -latexoption=-file-line-error -output-directory=../build/ -latexoption=-interaction=nonstopmode -usepretex=\providecommand{\commitId}{${{ steps.sha.outputs.sha_short }}}
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PUBLISH_TOKEN }}
          publish_dir: ./build
